# Generated by Django 3.1.6 on 2021-03-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstat',
            unique_together={('player', 'team')},
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='league',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='season',
        ),
    ]
