# Generated by Django 3.1.6 on 2021-03-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210311_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(max_length=10),
        ),
    ]
