# Generated by Django 3.1.6 on 2021-03-13 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210312_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='web.team'),
        ),
    ]
