# Generated by Django 3.1.6 on 2021-03-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=2, null=True)),
                ('flag', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('league_type', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='web.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=10, null=True)),
                ('weight', models.CharField(max_length=10, null=True)),
                ('birthdate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='web.country')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(unique=True)),
                ('end_year', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='web.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.season')),
            ],
            options={
                'unique_together': {('team_id', 'league', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[(1, 'attacker'), (2, 'midfielder'), (3, 'defender'), (4, 'goalkeeper'), (5, 'none')], max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shots', models.IntegerField()),
                ('shots_on_target', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('goals_conceded', models.IntegerField()),
                ('goals_saved', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('passes', models.IntegerField()),
                ('passes_key', models.IntegerField()),
                ('passes_accuracy', models.DecimalField(decimal_places=1, max_digits=4)),
                ('blocks', models.IntegerField()),
                ('tackles', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('duels', models.IntegerField()),
                ('duels_won', models.IntegerField()),
                ('dribbles_attempted', models.IntegerField()),
                ('dribbles_succeeded', models.IntegerField()),
                ('fouls_drawn', models.IntegerField()),
                ('fouls_committed', models.IntegerField()),
                ('yellows', models.IntegerField()),
                ('reds', models.IntegerField()),
                ('penalties_won', models.IntegerField()),
                ('penalties_committed', models.IntegerField()),
                ('penalties_scored', models.IntegerField()),
                ('penalties_taken', models.IntegerField()),
                ('penalties_saved', models.IntegerField()),
                ('appearances', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('benches', models.IntegerField()),
                ('minutes_played', models.IntegerField()),
                ('substitutions_in', models.IntegerField()),
                ('substitutions_out', models.IntegerField()),
                ('shots_on_target_pct', models.DecimalField(decimal_places=1, max_digits=4)),
                ('duels_won_pct', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dribbles_succeeded_pct', models.DecimalField(decimal_places=1, max_digits=4)),
                ('penalties_scored_pct', models.DecimalField(decimal_places=1, max_digits=4)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='web.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.team')),
            ],
            options={
                'unique_together': {('player', 'team', 'league', 'season')},
            },
        ),
    ]
