# Generated by Django 3.1.6 on 2021-03-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210312_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='dribbles_succeeded_pct',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='duels_won_pct',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='penalties_scored_pct',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='shots_on_target_pct',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
