# Generated by Django 3.1.6 on 2021-03-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210313_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='passes_accuracy',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
